// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtCcF9dOpftRVRhVBZPJiz3QMU-QDoam0',
    appId: '1:53013504420:web:dd9b177304346063402131',
    messagingSenderId: '53013504420',
    projectId: 'test-9f079',
    authDomain: 'test-9f079.firebaseapp.com',
    storageBucket: 'test-9f079.appspot.com',
    measurementId: 'G-NK60X9CHF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BLHmWWr7DWDm7-JIHFZpJgzd94BKF5k',
    appId: '1:53013504420:android:0d02bf7a8e5c98e6402131',
    messagingSenderId: '53013504420',
    projectId: 'test-9f079',
    storageBucket: 'test-9f079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedminTq-Yg7wPrVWpoGgRZFzm3TcEi38',
    appId: '1:53013504420:ios:1c5456226a870aea402131',
    messagingSenderId: '53013504420',
    projectId: 'test-9f079',
    storageBucket: 'test-9f079.appspot.com',
    iosClientId: '53013504420-1lg66bn3j28sc58c45po8f8ao2583276.apps.googleusercontent.com',
    iosBundleId: 'com.OmegaLabs.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAedminTq-Yg7wPrVWpoGgRZFzm3TcEi38',
    appId: '1:53013504420:ios:1c5456226a870aea402131',
    messagingSenderId: '53013504420',
    projectId: 'test-9f079',
    storageBucket: 'test-9f079.appspot.com',
    iosClientId: '53013504420-1lg66bn3j28sc58c45po8f8ao2583276.apps.googleusercontent.com',
    iosBundleId: 'com.OmegaLabs.mynotes',
  );
}
